parameters:
#    robin_address_book.example.class: Robin\AddressBookBundle\Example

services:
#    robin_address_book.example:
#        class: %robin_address_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
